workflows:
  ios-build:
    name: iOS Release Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic Key # Matches the exact API Key Name in Codemagic Team Settings
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.meet.minutes
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Set up code signing profiles
        script: xcode-project use-profiles
      - name: Build iOS IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
